---
################################################################################
# Template - Node CI
#
# Description:
#   This contains the basic information to: install dependencies, run tests,
#   get coverage, and run linting on a nodejs project. This template will run
#   over the MxN matrix of all operating systems, and all current LTS versions
#   of NodeJS.
#
# Dependencies:
#   This template assumes that your project is using the `tap` module for
#   testing. If you're not using this module, then the step that runs your
#   coverage will need to be adjusted.
#
################################################################################
name: Node CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Build
        uses: bahmutov/npm-install@4488656f8e90d3c85e3a964db0018dd624f340e7 # v1.11.1
        with:
          install-command: npm ci --foreground-scripts
      - name: Lint
        run: npm run lint
      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Test
        run: npm test
        env:
          DEBUG: 'package-lock-merge-driver*'
          FORCE_COLOR: '1'
